version: "3.2"
services:
  php:
    build:
      context: .
    image: author/t1php:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=t1php-mysql-app
      - MYSQL_USER=t1phpuser
      - MYSQL_PASSWORD=t1phppass
      - MYSQL_DB=t1php_db
    volumes:
      - ./:/var/www/html/
    ports:
      - "40001:80"
    container_name: t1php-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=t1phpuser
      - MYSQL_PASSWORD=t1phppass
      - MYSQL_DATABASE=t1php_db
    container_name: t1php-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "40002:80"
    environment:
      - PMA_HOST=t1php-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: t1php-phpmyadmin-app
networks:
  frontend:
  backend:
